name: Deploy to EC2 2

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          printf "%s" "${{ secrets.EC2_KEY }}" > ~/.ssh/ec2_key.pem
          chmod 600 ~/.ssh/ec2_key.pem
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Copy source to EC2
        run: |
          rsync -avz -e "ssh -i ~/.ssh/ec2_key.pem -o StrictHostKeyChecking=no" ./ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:${{ secrets.APP_DIR }}

      - name: Install make on EC2
        run: |
          ssh -i ~/.ssh/ec2_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "sudo yum install -y make || (sudo apt-get update && sudo apt-get install -y make)"

      - name: Create .env file on EC2
        run: |
          ssh -i ~/.ssh/ec2_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
            echo 'NODE_ENV=${{ secrets.NODE_ENV }}' > ${{ secrets.APP_DIR }}/.env && \
            echo 'DATABASE_URL=${{ secrets.DATABASE_URL }}' >> ${{ secrets.APP_DIR }}/.env && \
            echo 'AWS_REGION=${{ secrets.AWS_REGION }}' >> ${{ secrets.APP_DIR }}/.env && \
            echo 'AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}' >> ${{ secrets.APP_DIR }}/.env && \
            echo 'AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}' >> ${{ secrets.APP_DIR }}/.env && \
            echo 'IAMPORT_REST_API_KEY=${{ secrets.IAMPORT_REST_API_KEY }}' >> ${{ secrets.APP_DIR }}/.env && \
            echo 'IAMPORT_REST_API_SECRET=${{ secrets.IAMPORT_REST_API_SECRET }}' >> ${{ secrets.APP_DIR }}/.env && \
            echo 'JWT_SECRET=${{ secrets.JWT_SECRET }}' >> ${{ secrets.APP_DIR }}/.env && \
            echo 'JWT_EXPIRES_IN=${{ secrets.JWT_EXPIRES_IN }}' >> ${{ secrets.APP_DIR }}/.env && \
            echo 'DATABASE_CONTAINER_URL=${{ secrets.DATABASE_CONTAINER_URL }}' >> ${{ secrets.APP_DIR }}/.env
          "

      - name: Run deploy script via Makefile
        run: |
          ssh -i ~/.ssh/ec2_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "cd ${{ secrets.APP_DIR }} && make up"
